interface TableHeaderType {
  name: string;
}

export const TABLE_HEADER: TableHeaderType[] = [
  { name: '주간선도로' },
  { name: '보조간선도로' },
  { name: '집산도로' },
  { name: '국지도로' },
  { name: '차로폭' },
  { name: '갓길폭' },
  { name: '도로선형' },
  { name: '도로경사' },
  { name: '차로수' },
  { name: '도로포장' },
  { name: '노면상태' },
  { name: '도로유형' },
  { name: '중앙분리대' },
  { name: '방호울타리' },
  { name: '충격흡수시설' },
  { name: '연속조명' },
  { name: '국부조명' },
  { name: '과속방지턱' },
  { name: '차량신호' },
  { name: '도로상태예고' },
  { name: '노면상황예고' },
  { name: '기상상황예고' },
  { name: '기타주의예고' },
  { name: '통행금지' },
  { name: '통행제한' },
  { name: '금지사항' },
  { name: '도로지정' },
  { name: '통행방법' },
  { name: '기타지정' },
  { name: '중앙선' },
  { name: '차선' },
  { name: '사전예고표시' },
  { name: '안전속도표시' },
  { name: '금지구역표시' },
  { name: '최고제한속도' },
  { name: '최저제한속도' },
  { name: '보호구역' },
  { name: '전용도로' },
  { name: '도로공사' },
  { name: '선행사고' },
  { name: '장애물' },
  // Layer 4 start
  { name: '객채 수' },
  // 객체 종류
  { name: 'NPC1 객체종류' },
  { name: 'NPC2 객체종류' },
  { name: 'NPC3 객체종류' },
  { name: 'Ego 객체종류' },
  // Trigger 활성화 객체 선정
  { name: 'TN1방향' },
  { name: 'TN1차로' },
  { name: 'TN1속도' },
  { name: 'TN1거리' },
  { name: 'TN2방향' },
  { name: 'TN2차로' },
  { name: 'TN2속도' },
  { name: 'TN2거리' },
  { name: 'TN3방향' },
  { name: 'TN3차로' },
  { name: 'TN3속도' },
  { name: 'TN3거리' },
  // 행동정의(Action)
  { name: 'ALASADDS' },
  { name: 'ALASADTDD' },
  { name: 'ALASADN1거리' },
  { name: 'ALASADN2거리' },
  { name: 'ALASADN3거리' },
  { name: 'ALASADV' },
  { name: 'ALASATDS' },
  { name: 'ALASATDD' },
  { name: 'ALASATN1거리' },
  { name: 'ALASATN2거리' },
  { name: 'ALASATN3거리' },
  { name: 'ALASAT목표 속도' },
  //
  { name: 'ALA직진LCADS' },
  { name: 'ALA직진LCADD' },
  { name: 'ALA직진LCAN1거리' },
  { name: 'ALA직진LCAN2거리' },
  { name: 'ALA직진LCAN3거리' },
  { name: 'ALA직진TLCADS' },
  { name: 'ALA직진TLCATDD' },
  { name: 'ALA직진TLCAN1거리' },
  { name: 'ALA직진TLCAN2거리' },
  { name: 'ALA직진TLCAN3거리' },
  { name: 'ALA직진TLCA목표차선' },
  //
  { name: 'ALA죄회전LCADS' },
  { name: 'ALA죄회전LCADD' },
  { name: 'ALA죄회전LCAN1거리' },
  { name: 'ALA죄회전LCAN2거리' },
  { name: 'ALA죄회전LCAN3거리' },
  { name: 'ALA죄회전TLCADS' },
  { name: 'ALA죄회전TLCATDD' },
  { name: 'ALA죄회전TLCAN1거리' },
  { name: 'ALA죄회전TLCAN2거리' },
  { name: 'ALA죄회전TLCAN3거리' },
  { name: 'ALA죄회전TLCA목표차선' },
  //
  { name: 'ALA우회전LCADS' },
  { name: 'ALA우회전LCADD' },
  { name: 'ALA우회전LCAN1거리' },
  { name: 'ALA우회전LCAN2거리' },
  { name: 'ALA우회전LCAN3거리' },
  { name: 'ALA우회전TLCADS' },
  { name: 'ALA우회전TLCATDD' },
  { name: 'ALA우회전TLCAN1거리' },
  { name: 'ALA우회전TLCAN2거리' },
  { name: 'ALA우회전TLCAN3거리' },
  { name: 'ALA우회전TLCA목표차선' },
  // 이벤트 종료 조건
  { name: 'EECTSR' }, // TargetSpeedReached
  { name: 'EECTDAN1' },
  { name: 'EECTDAN2' },
  { name: 'EECTDAN3' },
  { name: 'EECTE' }, // TimeElapsed
  { name: 'EECEC' },
  // Layer 4 end
  { name: '시간대' },
  { name: '요일' },
  { name: '날씨' },
  { name: '기온' },
  { name: '조도' },
  { name: 'Camera센서' },
  { name: 'Radar센서' },
  { name: 'LiDAR센서' },
  { name: 'V2I' },
  { name: 'V2V' },
  { name: 'V2P' },
  { name: 'V2N' },
  { name: 'V2C' },
  { name: 'GPS정보' },
  { name: '전자지도정보' },
] as const;
