interface TableHeaderType {
  id: number;
  name: string;
}

export const TABLE_HEADER: TableHeaderType[] = [
  { id: 13, name: '주간선도로' },
  { id: 14, name: '보조간선도로' },
  { id: 15, name: '집산도로' },
  { id: 16, name: '국지도로' },
  { id: 17, name: '차로폭' },
  { id: 18, name: '갓길폭' },
  { id: 19, name: '도로선형' },
  { id: 20, name: '도로경사' },
  { id: 21, name: '차로수' },
  { id: 22, name: '도로포장' },
  { id: 23, name: '노면상태' },
  { id: 12, name: '도로유형' },
  { id: 87, name: '중앙분리대' },
  { id: 88, name: '방호울타리' },
  { id: 89, name: '충격흡수시설' },
  { id: 90, name: '연속조명' },
  { id: 91, name: '국부조명' },
  { id: 74, name: '과속방지턱' },
  { id: 94, name: '차량신호' },
  { id: 95, name: '도로상태예고' },
  { id: 96, name: '노면상황예고' },
  { id: 97, name: '기상상황예고' },
  { id: 98, name: '기타주의예고' },
  { id: 99, name: '통행금지' },
  { id: 100, name: '통행제한' },
  { id: 101, name: '금지사항' },
  { id: 102, name: '도로지정' },
  { id: 103, name: '통행방법' },
  { id: 104, name: '기타지정' },
  { id: 79, name: '중앙선' },
  { id: 80, name: '차선' },
  { id: 81, name: '사전예고표시' },
  { id: 82, name: '안전속도표시' },
  { id: 83, name: '금지구역표시' },
  { id: 118, name: '최고제한속도' },
  { id: 119, name: '최저제한속도' },
  { id: 85, name: '보호구역' },
  { id: 86, name: '전용도로' },
  { id: 174, name: '도로공사' },
  { id: 175, name: '선행사고' },
  { id: 176, name: '장애물' },
  // Layer 4 start
  { id: 183, name: '객체 수' },
  // 객체 종류
  { id: 205, name: 'NPC1 객체종류' },
  { id: 206, name: 'NPC2 객체종류' },
  { id: 207, name: 'NPC3 객체종류' },
  { id: 208, name: 'Ego 객체종류' },
  // Trigger 활성화 객체 선정
  { id: 283, name: 'TN1방향' },
  { id: 284, name: 'TN1차로' },
  { id: 260, name: 'TN1속도' },
  { id: 261, name: 'TN1거리' },
  { id: 300, name: 'TN2방향' },
  { id: 301, name: 'TN2차로' },
  { id: 263, name: 'TN2속도' },
  { id: 264, name: 'TN2거리' },
  { id: 317, name: 'TN3방향' },
  { id: 318, name: 'TN3차로' },
  { id: 266, name: 'TN3속도' },
  { id: 267, name: 'TN3거리' },
  // 행동정의(Action)
  { id: 268, name: 'ALASADDS' },
  { id: 269, name: 'ALASADTDD' },
  { id: 474, name: 'ALASADN1거리' },
  { id: 476, name: 'ALASADN2거리' },
  { id: 478, name: 'ALASADN3거리' },
  { id: 270, name: 'ALASADV' },
  { id: 271, name: 'ALASATDS' },
  { id: 272, name: 'ALASATDD' },
  { id: 480, name: 'ALASATN1거리' },
  { id: 482, name: 'ALASATN2거리' },
  { id: 484, name: 'ALASATN3거리' },
  { id: 273, name: 'ALASAT목표 속도' },
  //
  { id: 426, name: 'ALA직진LCADS' },
  { id: 427, name: 'ALA직진LCADD' },
  { id: 657, name: 'ALA직진LCAN1거리' },
  { id: 659, name: 'ALA직진LCAN2거리' },
  { id: 661, name: 'ALA직진LCAN3거리' },
  { id: 428, name: 'ALA직진TLCADS' },
  { id: 429, name: 'ALA직진TLCATDD' },
  { id: 681, name: 'ALA직진TLCAN1거리' },
  { id: 683, name: 'ALA직진TLCAN2거리' },
  { id: 685, name: 'ALA직진TLCAN3거리' },
  { id: 513, name: 'ALA직진TLCA목표차선' },
  //
  { id: 431, name: 'ALA좌회전LCADS' },
  { id: 432, name: 'ALA좌회전LCADD' },
  { id: 663, name: 'ALA좌회전LCAN1거리' },
  { id: 665, name: 'ALA좌회전LCAN2거리' },
  { id: 667, name: 'ALA좌회전LCAN3거리' },
  { id: 433, name: 'ALA좌회전TLCADS' },
  { id: 434, name: 'ALA좌회전TLCATDD' },
  { id: 687, name: 'ALA좌회전TLCAN1거리' },
  { id: 689, name: 'ALA좌회전TLCAN2거리' },
  { id: 691, name: 'ALA좌회전TLCAN3거리' },
  { id: 569, name: 'ALA좌회전TLCA목표차선' },
  //
  { id: 436, name: 'ALA우회전LCADS' },
  { id: 437, name: 'ALA우회전LCADD' },
  { id: 669, name: 'ALA우회전LCAN1거리' },
  { id: 671, name: 'ALA우회전LCAN2거리' },
  { id: 673, name: 'ALA우회전LCAN3거리' },
  { id: 438, name: 'ALA우회전TLCADS' },
  { id: 439, name: 'ALA우회전TLCATDD' },
  { id: 675, name: 'ALA우회전TLCAN1거리' },
  { id: 677, name: 'ALA우회전TLCAN2거리' },
  { id: 679, name: 'ALA우회전TLCAN3거리' },
  { id: 569, name: 'ALA우회전TLCA목표차선' },
  // 이벤트 종료 조건
  { id: 201, name: 'EECTSR' }, // TargetSpeedReached
  { id: 380, name: 'EECTDAN1' },
  { id: 382, name: 'EECTDAN2' },
  { id: 384, name: 'EECTDAN3' },
  { id: 203, name: 'EECTE' }, // TimeElapsed
  { id: 204, name: 'EECEC' },
  // Layer 4 end
  { id: 913, name: '시간대' },
  { id: 914, name: '요일' },
  { id: 915, name: '날씨' },
  { id: 916, name: '기온' },
  { id: 917, name: '조도' },
  { id: 937, name: 'Camera센서' },
  { id: 938, name: 'Radar센서' },
  { id: 939, name: 'LiDAR센서' },
  { id: 940, name: 'V2I' },
  { id: 941, name: 'V2V' },
  { id: 942, name: 'V2P' },
  { id: 943, name: 'V2N' },
  { id: 944, name: 'V2C' },
  { id: 945, name: 'GPS정보' },
  { id: 946, name: '전자지도정보' },
  { id: 7, name: '법ㆍ규제' },
] as const;
